title: "Data 101"
only_build_toc_files: true

sphinx:
  builder: singlehtml
  config:
    html_theme: "sphinx_book_theme"
    html_theme_options:
      use_repository_button: false
      use_issues_button: false
      use_edit_page_button: false
      show_navbar_depth: 2       # Needed for nested headers
      show_toc_level: 3          # Include h3 headers in sidebar
      sidebars: ["sidebar-nav-bs", "page-toc"]  # ✅ Enables right-hand ToC
      search_bar_text: "Search this book..."
html_theme_options:
  collapse_navigation: true      # Auto-collapse nested entries
  navigation_depth: 2            # Limit sidebar levels
  sidebar_hide_name: true        # Hide the page title in sidebar
  default_sidebar: "collapsed"   # ✅ Auto closes the sidebar on load
